/**
 * Pre-computed 24×24 pixel-art bitmap of the Sam Merkovitz SM monogram.
 * Generated by scripts/pixelize-logo.mjs from public/sam-logo-black.svg.
 * Used anywhere we want an 8-bit rendering of the brand mark.
 */

const BITMAP = [
  "························",
  "··███████████·████████··",
  "·████████████··████████·",
  "·██········███··███·███·",
  "·██·█████··████·██··███·",
  "·██·██████·████····████·",
  "·██·██··██·██·██··█████·",
  "·██·██··██·██·███·██·██·",
  "·██·███··█·██··████··██·",
  "·██··███···██···███··██·",
  "·███··███··██···██···██·",
  "··███···██··█·█····█·██·",
  "···███···███··██··██·██·",
  "·█···██···███·██··██·██·",
  "·██···███··██·██··██·██·",
  "·██·█··███·██·██··██·██·",
  "·██·██··██·██·██··██·██·",
  "·██·██··██·██·██··██·██·",
  "·██·██████·██·██··██·██·",
  "·██·█████··██·██··██·██·",
  "·██········██·██··██·██·",
  "·████████████·█████████·",
  "··██████████·█████████··",
  "························",
] as const;

const SIZE = BITMAP.length;

export const PIXEL_MARK_SIZE = SIZE;

interface PixelMarkProps {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

export default function PixelMark({ size = 24, className, style }: PixelMarkProps) {
  return (
    <svg
      viewBox={`0 0 ${SIZE} ${SIZE}`}
      width={size}
      height={size}
      shapeRendering="crispEdges"
      fill="currentColor"
      className={className}
      style={{ imageRendering: "pixelated", ...style }}
      aria-hidden="true"
    >
      {BITMAP.flatMap((row, y) =>
        row.split("").map((cell, x) =>
          cell === "█" ? <rect key={`${x}-${y}`} x={x} y={y} width="1" height="1" /> : null,
        ),
      )}
    </svg>
  );
}
